"""Convert a .tflite flatbuffer into a C++ header for ESP32 firmware embedding.

The generated header declares an 8-byte-aligned ``g_model_data[]`` array
and a ``g_model_data_len`` constant, both of which the firmware
references in esp32_firmware/src/main.cpp.

8-byte alignment is mandatory: ``tflite::GetModel`` reads multibyte
fields from the FlatBuffer assuming aligned access, and an unaligned
array will crash with a LoadStoreAlignment fault on Xtensa.  This is why
we don't use ``xxd -i`` directly.

Usage:
    uv run python scripts/embed_tflite_model.py \\
        runs/full/mobilenet_v3_small/model.tflite \\
        --output esp32_firmware/src/model_data.h
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

HEADER_TEMPLATE = """\
// Auto-generated by scripts/embed_tflite_model.py at {timestamp}.
// Source model: {src}
// Size: {size} bytes ({size_kb} KB)
//
// Regenerate after re-running scripts/04_export_all.py; do not edit by hand.

#pragma once

#include <cstddef>

// 8-byte alignment is required by tflite::GetModel().  An unaligned model
// array crashes the Xtensa CPU with a LoadStoreAlignment fault.
alignas(8) const unsigned char g_model_data[] = {{
{bytes}
}};

constexpr size_t g_model_data_len = sizeof(g_model_data);
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tflite_path", type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("esp32_firmware/src/model_data.h"),
    )
    args = parser.parse_args()

    data = args.tflite_path.read_bytes()
    chunks = []
    for i in range(0, len(data), 16):
        line = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
        chunks.append(f"    {line},")
    body = HEADER_TEMPLATE.format(
        timestamp=dt.datetime.now().isoformat(timespec="seconds"),
        src=args.tflite_path,
        size=len(data),
        size_kb=len(data) // 1024,
        bytes="\n".join(chunks),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    print(f"[ok] wrote {len(data)} bytes -> {args.output}")


if __name__ == "__main__":
    main()
